signUp and signIn design
STA-Development/Social_network pull request #1
Opened 2022-12-30 15:18 UTC by AmirBandarii

2023-01-19 17:20 UTC, gor017 requested changes

2023-01-19 17:20 UTC, gor017 commented on .gitignore
> +./.idea
Also all files in idea folder should be in git ignore and not be visible in pull request

2023-01-19 17:20 UTC, gor017 commented on src/App.tsx
> +    <GlobalContext.Provider value={{}}>
Why value is empty?

2023-01-19 17:20 UTC, gor017 commented on src/components/formPages/colorButton.ts
> +export const LogIn = {
Use more defining name for understanding what that variable is. For example is it for UI or it's for functionality.

2023-01-19 17:20 UTC, gor017 commented on src/components/formPages/login/LoginPage.css
> +.backGroundLogin {
background is one word

2023-01-19 17:20 UTC, gor017 commented on src/components/formPages/login/LoginPage.css
> +.LineSize{
if you decided to use lowercase names for classes, use lowercase for all of them

2023-01-19 17:20 UTC, gor017 commented on src/components/formPages/login/LoginPage.tsx
> +            <p>Welcome Back ! Please enter your details</p>
Use MUI components for these

2023-01-19 17:20 UTC, gor017 commented on src/components/formPages/login/LoginPage.tsx
> +            <hr className='LineSize' />
Also for them, for example use MUI Divider component instead of <hr />

2023-01-19 17:20 UTC, gor017 commented on src/components/formPages/login/LoginPage.tsx
> +            <p>Forget Password</p>
also here use MUI Typography, and for all p tags

2023-01-19 17:20 UTC, gor017 commented on src/components/formPages/login/LoginPage.tsx
> +        <div className='loginScreen'>
use Box instead of div

2023-01-19 17:20 UTC, gor017 commented on src/components/formPages/signUp/SignUp.css
> +    width : 60%;
use lowercase for names if all class names are lowercase

2023-01-19 17:20 UTC, gor017 commented on src/components/formPages/signUp/SignUp.css
> +}
Run prettier for all project for having beautiful and comfortable code, because there are place where you put space and there are places where you didn't.

2023-01-19 17:20 UTC, gor017 commented on src/components/formPages/signUp/SignUpPage.tsx
> +            autoComplete='off'
For what is that?

2023-01-19 17:20 UTC, gor017 commented on src/components/formPages/signUp/SignUpPage.tsx
> +              '& > :not(style)': { m: 1 },
What is not(style)?

2023-01-19 17:20 UTC, gor017 commented on src/components/home/PostPage.css
> +
Use more defining names

2023-01-19 17:20 UTC, gor017 commented on src/components/home/PostsPage.tsx
> +};
Use MUI components

2023-01-19 17:20 UTC, gor017 commented on src/components/home/navbar/Navbar.tsx
> +  const [anchorElUser, setAnchorElUser] = React.useState<null | HTMLElement>(null);
Import hooks and use them independently without React.

2023-01-20 11:27 UTC, gor017 requested changes

2023-01-20 11:27 UTC, gor017 commented on src/components/formPages/colorButton.ts
> +};
Make styles and use variables for colors and also margins and paddings.

2023-01-20 18:38 UTC, gor017 requested changes

2023-01-20 18:38 UTC, gor017 commented on src/components/formPages/login/LoginPage.css
> +}
Use variables for styling

2023-01-20 18:38 UTC, gor017 commented on src/components/formPages/login/LoginPage.tsx
> +            <hr className='lineSize' />
Use Divider instead of hr

2023-01-20 18:38 UTC, gor017 commented on src/components/formPages/login/LoginPage.tsx
> +              <span style={{ marginLeft: '5px' }}>Log in with google</span>
Don't use span

2023-01-20 18:38 UTC, gor017 commented on src/components/formPages/login/LoginPage.tsx
> +          <img className='loginImageScreen' src={moon} alt='moon' />
Create component for images, and call component.

2023-01-20 18:38 UTC, gor017 commented on src/components/formPages/signUp/SignUpPage.tsx
> +              className='TextFieldColor'
Don't use span and hr

2023-01-20 18:38 UTC, gor017 commented on src/components/formPages/signUp/SignUpPage.tsx
> +            {errors.lastName && <p style={{ color: 'red' }}>lastName is required!</p>}
Don't use p

2023-01-20 18:38 UTC, gor017 commented on src/components/formPages/signUp/SignUpPage.tsx
> +  );
Use components for images

2023-01-20 18:38 UTC, gor017 commented on src/components/formPages/signUp/SignUpPage.tsx
> +              defaultValue={password}
Same here

2023-01-20 18:38 UTC, gor017 commented on src/components/home/PostsPage.tsx
> +      </Box>
Same

2023-01-26 14:01 UTC, gor017 requested changes

2023-01-26 14:01 UTC, gor017 commented on src/assets/images/Friends.tsx
> +  return <img style={{ width: '300px', height: '250px' }} src={happy} alt='Friends' />;
same here

2023-01-26 14:01 UTC, gor017 commented on src/assets/images/Happy.tsx
> +};
same here

2023-01-26 14:01 UTC, gor017 commented on src/assets/images/Moon.tsx
> +};
same here

2023-01-26 14:01 UTC, gor017 commented on src/assets/images/Nature.tsx
> +};
same here

2023-01-26 14:01 UTC, gor017 commented on src/assets/variables/index.ts
> +
it's wrong way to use style variables, use more defining variables for example 
const padding  = {
      top10: '10px'
}
and use this one if you need to give padding top 10px

2023-01-26 14:01 UTC, gor017 commented on src/components/formPages/login/LoginPage.tsx
> +  };
remove console.log s

2023-01-26 14:01 UTC, gor017 commented on src/components/formPages/login/LoginPage.tsx
> +  };
use variables for styling

2023-01-26 14:01 UTC, gor017 commented on src/components/formPages/login/LoginPage.tsx
> +            >
don't write and type=submit if you wrote type=submit do your other actions in onSubmit function

2023-01-26 14:01 UTC, gor017 commented on src/components/formPages/signUp/SignUpPage.tsx
> +  };
remove console.log

2023-01-26 14:01 UTC, gor017 commented on src/components/formPages/signUp/SignUpPage.tsx
> +              sx={LogInButtonUI}
I think this will not work

2023-01-26 14:01 UTC, gor017 commented on src/components/formPages/signUp/SignUpPage.tsx
> +              type='submit'
Don't write onClick in submit button

2023-01-26 14:01 UTC, gor017 commented on src/components/home/PostsPage.tsx
> +        <Box className='AddButton'></Box>
I think this box isn't needed

2023-01-26 14:01 UTC, gor017 commented on src/assets/images/Cloud.tsx
> +};
Use more defining names, for understanding what component that is during calling that.
For example FriendsPicture

2023-01-26 14:01 UTC, gor017 commented on src/assets/variables/index.ts
> +
Use MUI makeStyles for all stylings

2023-01-26 14:01 UTC, gor017 commented on src/components/formPages/login/LoginPage.tsx
> +              sx={LogInButtonUI}
I think this will not work

2023-01-26 14:01 UTC, gor017 commented on src/components/home/navbar/Navbar.tsx
> +                <MenuItem key={setting} onClick={handleCloseUserMenu}>
don't give the same item to the key, key should be unique

2023-01-26 14:01 UTC, gor017 commented on src/context/CreateContext.tsx
> +export const GlobalContext = createContext({});
you created context but never used it, why do you keep it?

2023-02-03 15:56 UTC, AmirBandarii commented on src/components/formPages/colorButton.ts
> +};
all of this style I've taken only for changing color of button

2023-02-03 15:56 UTC, AmirBandarii commented on src/components/formPages/signUp/SignUpPage.tsx
> +              '& > :not(style)': { m: 1 },
The :not() pseudo-class requires a comma-separated list of one or more selectors as its argument

2023-02-03 15:56 UTC, AmirBandarii commented on src/components/axios/api.ts
> +  return await axios.post('http://localhost:5000/api/usersInformation/login', usersInfo);
You should get the url of BE from process.env

2023-02-03 15:56 UTC, AmirBandarii commented on src/components/axios/axios.ts
> +  baseURL: 'http://localhost:5000/api/',
Here too

2023-02-03 15:56 UTC, AmirBandarii commented on src/components/formPages/login/LoginPage.tsx
> +    return(data)
Put in try catch

2023-02-03 15:56 UTC, AmirBandarii commented on src/components/formPages/login/LoginPage.tsx
> +                  /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
It's not looking good in component, can we keep this as variable in top or create seperate helper file with this kind of things?

2023-02-03 15:56 UTC, AmirBandarii commented on src/components/formPages/login/LoginPage.tsx
> +                pattern: /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$/,
Move to the helper file

2023-02-03 15:56 UTC, AmirBandarii commented on src/components/formPages/signUp/SignUpPage.tsx
> +    return response;
Make every request to BE in try catch

2023-02-03 15:56 UTC, AmirBandarii commented on src/components/formPages/signUp/SignUpPage.tsx
> +    justifyContent: 'center',
Too much styling in component, create styled component and use it

2023-02-03 15:56 UTC, AmirBandarii commented on src/components/formPages/signUp/SignUpPage.tsx
> +                  /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
use from helper

2023-03-21 16:04 UTC, merged